language: node_js
os: linux
sudo: false
dist: xenial
group: travis_lts
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
node_js:
  - '10'
script:
  - npm run demo
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
